language: node_js

node_js:
  - 12.18.3

services:
  - postgresql

env:
  global:
    - secure: "p3wBtpcn6X2ZUqGuOshxUZASgB7E4rOu38R3v9wASm2qN6d/e8ysKyA222AsxsMCNeMtCYQr+Ac6km54GFL8bin5w/DKWl5Px3bERqNcY2rLRAYs9od1Q1UTAcDkwDzcJn7F+WjC4OSLfOyVLEwvimE6nZ/9WjnVqyL9KQ1feMgM8iTsjZUwUHkzC05tx/sqXxvAXIeJ9a4XNqr85UemPon6CDJy1olayJ4GSyxeFlLrAlhukiDOuYPMz7dJoKKn4U6D+IfQ1OU9deadacnEoZrq+x8ueZAufnl99ebz3WBnxDFnFD2uLF0ZuYCB6j64Kop8iiMsYrVhmZ+Ad/d07/u5qmsfF1G8c5O/3IfjS4SbFjA0yMB+bT3xBSYmUM5bw6oPi8RUKg0UnpAUgH9LsnJ0sYTKJ+WPLR8H/hDCR2xh/rfCbYQqHh/6R/X84CdFWa5uCRCzvakrwusiZoXJUdT7riaMkNJABZyhhutf8xcLWuiTljIqNph6u/Gjk6ojGGwthyrYqH+CdKnNdaQM6E/D3wKn9+pitvJvruahMXKriDPc54Xy2Yxhm3MyyyEY+VENGSBdf0lMS2n2lLAme6ihepzAlB4ngUeovPFSPiK+YKzvFFVdSC6c0utRG5FLpDBW8XiGz12Z6grNPw4c4fw0yGEcKeAzT+I80kbiYCI="
    - OPENING_HOUR=8
    - OPENING_MINUTE=30
    - CLOSING_HOUR=16
    - CLOSING_MINUTE=00
    - EXPIRY=2000
    - secure: "uUSk3Jsnav2hAVkbXb3xluP1WhaRHdkjAOtb85UJV6ao0mwj3rOYzyjYbVUC1BqIHjfgeo6Cx/DynmvQnUMb0buuan273W5y8ZrIFKvFuFlSpP8u+O0zT7MeAjMLoIOUtYexuHlIMJs+Ij52vXkgLJrU9FrViWPPZ2r3fIjC2EUiORnvjUaEKeyF1cNspDFLzivziYfP22jtfKLoAXQpI4zagFoXLUopLGBcWbxiyxqcw43u1k8Nki9o8WSpdR+I8HSbGSFrg02AxvVFTnpmh7CV66JiHYGvrM5CmWrWPBsVM24WQPy8Uswpiq84aFC2YYeI9eIndS1SJ0H8Iod0AXT6A01Cn5eqpyUHbFR1oor4hYvX0NmsXN1eemhLOt2gzjqCITN8be1oubCeKSmWSkTAnS36ERHGrcXq7HXXrQeI851o+X1M2FU9os9pSQEoL83VXKoqfRr96B/hGyjMTEABh4IHRcPTlRQJUWeEB+NBnPkFnOGQ+dHtsON6j12bOMN5WjLfr3M8Ex+lrO2D3K9/RHN5YA0B/vBH/i4UuicjuKNVho42OnVaaYQrkTyb6brEtPr+/eWekuaTLZb3g1JXlrFcC3DirzUvSd8qTU0Xn/wsOar0ACLvKJr2HZDmtf1Fh8QB+ene3BxBW52NjftZb/sS2Moj2kLD1ToyDCA="
    - secure: "uZxtdHkGECu296/sBnwGQ60+XEyFMnpe6LN8Zb85V4TOqoqsvbQvJ+dY4ZQtRU6H39KnUtAKsIrzMqvkgndunNE4eyfb+mdFP3Wqju3MvYRQ06CLTqU8khjYFbfN+BAECtVywAu5M+k2U0Bgim7uZ+R8oaN2Y1nUAK6hio6AIiYtvYqOIfMqmr6qM8mtXqKNLhD+0T+H38GMAdcOW2TkltlMnij0FcZ4mmdlWuANCHHLs6jgegtNfnUHiFYoduThCzSrLuxXvarfwhh56XxhZta/JqL5ArONMnDyzz4ZXY5YMFLm11SdWhJ/ypNeTdD2b+4sfvzX8PUUYcM0m6nl5ZTB2VcbBuLqVZo54vbgkF2OotSaQltrEEkJLyBm8/NgbgA1LOovyVekAQ2mRAWBbgAKysd+LSpPKIyeotgMWw5UsWYOzmcyH2N8WhqDb+vFJwqXASVxQbyzLgJ+n60Ya8312hEu3toxwlnGjTuwDqs2RfRDwOWglRwqRrTyJ5tk7C5KcKTpHFEj3MxByv0w/nvD9ilowAOETfinTpxE3q3SepQBs1xFV9cuWZ0eSnSNHy/Ym/7NEvkK3k6KdHE45n3vuI6kxfgH+vBmkhe3wXXHKGuTqP7DgTAl+pgX/MuNH+/DZpOxi8SZuGnJRzr1H+nSThgVN3V5GUs8BWFv9zU="

cache:
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - psql -c 'create database book_a_meal_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - npm run build

script:
  - npm run test:coverage
  - ./cc-test-reporter format-coverage -t lcov ./packages/server/coverage/lcov.info --output ./packages/server/coverage/codeclimate.json
  - ./cc-test-reporter format-coverage -t lcov ./packages/server/coverage/lcov-v2.info  --output ./packages/server/coverage/codeclimate-v2.json
  - ./cc-test-reporter format-coverage -t lcov ./packages/client/coverage/lcov.info  --output ./packages/client/coverage/codeclimate.json
  - ./cc-test-reporter sum-coverage -p 3 ./packages/*/coverage/codeclimate.json ./packages/server/coverage/codeclimate-v2.json
  - ./cc-test-reporter upload-coverage

after_success:
  - npm run coverage

