language: node_js

node_js:
  - '9.11.1'

env:
  global:
    - CC_TEST_REPORTER_ID=1d64771979b17b23c6604237e6fa9e47f4ea993a33a4b938e04f3924925679bc
    - OPENING_HOUR=8
    - OPENING_MINUTE=30
    - CLOSING_HOUR=16
    - CLOSING_MINUTE=00
    - EXPIRY=1000

script:
  - npm run test

cache: 
  yarn: true
  directories:
    - 'node_modules'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - psql -c 'create database book_a_meal_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
after_success:
  - npm run coverage
  
